version: "3.9"  # optional since v1.27.0
services:
  bot:
    image: romasku/car-lookup-bot:latest
    environment:
      REDIS_URL: "redis://:envMBFIRANmC4yd8paX4Fw5tYKmWt2E0G6RGZbUL@redis:6379"
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    environment:
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=envMBFIRANmC4yd8paX4Fw5tYKmWt2E0G6RGZbUL
    volumes:
      - redis_data:/bitnami
volumes:
    redis_data:
