name: Deploy

on:
  push:
    branches:
      - main

jobs:
  my-job:
    name: Deploy to cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install requirements
        run: make setup
      - name: Run tests
        run: make test-unit
      - name: Build image
        run: make docker_build
      - name: Tag image
        run: docker tag railroad-ink-server:latest romasku/car-lookup-bot:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push romasku/car-lookup-bot:latest
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 129.159.248.24
          username: opc
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          script: ./deploy_bot.sh
